apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: activemq-artemis-operator.v1.0.0
  namespace: placeholder
  annotations:
    categories: "Messaging"
    certified: "false"
    description: ActiveMQ Artemis Operator can deploy headless service environments which exposed each of the ports, along with the statefulset.
    containerImage: quay.io/ahameed/activemq-artemis-operator:latest
    createdAt: 2019-03-20T20:48:22Z
    support: Red Hat, Inc.
    tectonic-visibility: ocs
    alm-examples: >-
      [{
       		"apiVersion": "broker.amq.io/v1alpha1",
       		"kind": "ActiveMQArtemis",
       		"metadata": {
       			"name": "example-activemqartemis",
       			"labels": {
       				"ActiveMQArtemis": "example-activemqartemis",
       				"application": "example-activemqartemis-app"
       			}
       		},
       		"spec": {
       			"size": "4",
       			"image": "registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:1.3-4"
       		}
       	},
       	{
       		"apiVersion": "broker.amq.io/v1alpha1",
       		"kind": "ActiveMQArtemisAddress",
       		"metadata": {
       			"name": "example-activemqartemisaddress",
       			"labels": {
       				"ActiveMQArtemis": "example-activemqartemis",
       				"application": "example-activemqartemis-app"
       			}
       		},
       		"spec": {
       			"statefulsetName": "example-activemqartemis-ss",
       			"addressName": "myAddress0",
       			"queueName": "myQueue0",
       			"routingType": "anycast"
       		}
       	}
       ]

  labels:
    operator-activemqartemis: "true"
spec:
  displayName: ActiveMQ Artemis
  description: ActiveMQ Artemis Operator can deploy headless service environments which exposed each of the ports, along with the statefulset.
  keywords:
    - activemqartemis
    - operator
  version: 1.0.0
  maturity: alpha
  maintainers:
    - name: Red Hat, Inc.
      email: rkieley@redhat.com
  provider:
    name: Red Hat, Inc.
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-amq/
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_amq/7.2/
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAAlwSFlzAAALEwAACxMBAJqcGAAAAVlpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IlhNUCBDb3JlIDUuNC4wIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6dGlmZj0iaHR0cDovL25zLmFkb2JlLmNvbS90aWZmLzEuMC8iPgogICAgICAgICA8dGlmZjpPcmllbnRhdGlvbj4xPC90aWZmOk9yaWVudGF0aW9uPgogICAgICA8L3JkZjpEZXNjcmlwdGlvbj4KICAgPC9yZGY6UkRGPgo8L3g6eG1wbWV0YT4KTMInWQAAC7hJREFUWAltV2t0VNUV/s69dybPyWsCIS9BIKlJyDIJDyEKggFEHrJcFV0FW9pVtIp01SIKkQrBosVHfeGz2roo9kdhtYII5RGSQMgbTACTYBIghAAJmUnmzkySedx7T/e5k6Cs9qx1586ce8/59v72t/fZw/B/BgdYxdy58ryKCm30cUtWVkZQ0meBsXs45xmMG+NZXMJkrbqeS3Z28Y4j9Z3xU6d1IBisg2HUsPDw9tG1vLxcwbx5OgNo69sHzd0+SgApewXYY3uhiydnszPugSStpq/LwiQpLVzsYnBosXHwnqqFlDkekz77O6LmzBGvm4MM7GacH6B1uxhjdWJyz54V8oqWHM5KSozQW6HP2wwg8ySa5gLjdGZmotUiPc8ZfzZOlm1+zjFsGOC6rrN4O9er65icOUEe8+obPGxShjF84wZXoqOYvaBAVqKjzd2HBwc9nsHBjyLGjn0rhjEHTTLBLu1/ywglZIfJjSSAhQFN2ZPzIbEPYmSp0EegLt0I0jTjuiZL9jGSTp7Ld93Jxrz6JgJBjV0uyJdErIQ3495+27jzyacMIzyMa4ZhS0hM3Hi9rGx2M7AuB2gUGMLRUSOExwJVrDXBv83NmMMkeX+CIhe6yFsfQHtzhcAVKWEM0xtrGZnPUj74DJFZ2eh5600RKxa+sIjJNrCb69dL109VKt6hIWUoGNRuVFfplt27CrUpP9l/HAjFiWLES0pMbGUE3KSlOScjT+fSlzGynD6g6QGySiF7ZQIHgYPAwYeA1MP/QWJRERynTyNw+gysc+6F4XRCnjEP2vFyeK9dQwTnLHDhgqIWbzT0UzV+cjDdsmjhl+0/W7WcdNG4glggM5i0d0WIjuacnASNsY8FuKqPgIuXdJ3AE6HX1wIEnnbsKJIeXCSIQ1h8AsIXLoDvZBWYRTHBBZURmZnwt7VB/cMm6NU1ktseYe0F/FP/tCN98sqVHxBw4l6YIpeVUbXrkrYxRlJmErgQiGBGgq5zEhzRXgdOKkg7ehRx98xE96FDGGxtRWxeHpKfXoseqxWBbw5CnjQecVu3g/l8UN97B1p5Jdzj4uHvGWDZx0stkXn5IrMKnWfObKD7JmJCEwajKSdzBv04bmUs2k86JzXIBA5GHhoXGsH7g0g9cgRj589H11f7cOnRn4plsNI18fhxWJJT4LjQivDUVGBwEN4Pd0L711dQx8bAd9ON7LIynjZvnsDS+o4cUa7sfN+jtbUsmNXeWWcKQYL0a5ssRQc4N5jBGTOI9vgEbpyrBwg8ed8+jF24EMGhITj3/ZuEAdh+vsrksK+a6E9JxpjFSyCTkrw73xsBt42CYwScw+Cyq7U1KB88ZEN752raBsr5KZMnGZwvDYjsFxnCDQmxCdBbGmg3IPngNxj70GLxLiRFQfSsQri+/AfYbrpoTkm/A5Ru8DXUQX1hPYza01CTYuHvVYXnAtxcyw2DMUniCQ89xGSqE7rdvuzm9OnvKJwps60MKQHaBBR+Kq9M//4M4OIY9/V+JAlw8kyIUQ4PR9ojj5h2uqtOIeL+uYh/4AEESHDuzZtgnCfw5Hj4bgwgq7T0x+AgcAwPDzMkJUnRDz+MyKioNMrvWQrBzrIQQEDXOIuLZ0ZbE8VcRwp5nkS0jg4my+bXiORkpK56AlELFkCx2xHo6IDrpY3Q66qhJoyAky7SyTAxhOFiLYHD4/bA0DWmRERoYRaLMvDddzMkivlkOjzAYuO53n6OGc4AUg4dNMGHb95ETxnl9ZUuczPxQeUVQ9xAWFqamWoDGzdArzoB9wh4dkXFLXARUQE+RNrxeAictCVTxpDg4aipQef27RnyM2Pit8ixCQnBtkYOZ4AlHzjAxi1ZAl9/P9q3bsW1364jYQ/CRikHip3b5TIL+XBTE9yU50ZDFdRYUnsPxbycYj53LjwXL6Fz1xcY7ukFS0iAj9JK8/shWyzm1U/F69qG30u+8god52bN0JrsVt5EB0TPgQOiSJrDUd/AK4jBk3RV0nV5337e7/XyHoeDd1VW8vMLi3iTDfzEGBs/Ss+7jh011/lVlTc9u5aXj6xr3b2b9/T08F5a1+d08u+PHuNl+fnGYXp+ougBTTIa6hkn2pMF7UuX3qI66s4JSCwupmoERK5ZA5l+60Spv6UZ6rYt0CuPwx0RA3+fB1mk9vT5C8y1GrFlOJzmOjGhEZNCgML7/oYGdBdvhNbYCCUvF9ytMkaet084fHhy7IMPigpIJ57ORgXndzjQd/48eGIiIiZMwPC5s1C3vkyCqyDwaAz3eZF17BiBzzfBzQ8qod0Uius730fYXVmwr1qFiPHj4aypRffGF6A3neXS9KlGuNov+8PC25ijqqrMXlgoktUYyVXKOdpFZIamwUvqpQzG8FkBvhn66RNQLZHwOYYw5dQppNx77w/g9M1Hsfa43RDGK5GRsMTHo7++HlefXw/t3Hko0wo4d7t0G2OKV1KOKgTeTuuEAYxACTl0Hx4aYkK5nKjzN38Ht/C8sRKqZL0FPq6gAP0kRgo+4rKyECTFqwMD5rkenpJiZoCT1N694XkTXJ5WQLS7KPoEQ+9S1euQgh5PreHsB/f7KTtMA+ATOUuxhDhkWlrgfqUEesNJqHREDA8EyPNKJFFWXPzbF2jJz0fH4vm4RNXRTWlLbRgdr0QiseesqroNnFKIeKZ+jrynsi+Ou3r5F5GRns5PP3lU93ptttxcHqQzWlVVBiq7/tYWqK9shX6qHCodxT6fgSmVJ5F632z0U0guUVVUkiJh9LoxVPo1rIuXIzI9jUgEBkho3cWboDWdhfDcBBfNpCwb4VSUqUHotsCyXcp4+eWLrn37vvF+/inUGzcYxZxaEBk+8lzdRuAnyshzIJifa3qeWhiKuVC2OJSkOzIhpcZDtEmSIlNfQGqnRqX7xQ3Qvm00wQXtdM5RcCmnKF5WWks0HLi/tbXd7AnHPfnk5+HLl69kMTHRdGBr5Lnk2baV65XlTKWCHcy7GxM3bwEbHELrjh2wUlbE5ObC/u67cDz3nJlycZ98gqiMDDhr68zipbV33AKnFl6UREboOh35Freue2RF3iWYosnQcLhcr9tsthd7a2oMdctmrp+tkVVngAdys1nmG38mTgfQtXKlKTCxIvLxFbA/9TS1RWEifxCZmQG1pRVX162FRvdR2oXnlNdCcIawgBpd2aMbO4raLhWLfSS+Z495ythjY3fcKC+vZR9/KOllJwy3GjCoIWU5f/krEqfkovezT01w6/33wVKQi6F/7jW7ougpUxAztQBqcwuu/m6dCa5MD6ldZIcAD8me/krIsuzWjeohKOQRUD53LintscfIfiFcNtAIPIOJqQeo1UkbDiCYXVrKk2fOlEVtD5afgJKTSX3hIFhMvEm7TvnOg6R2inXXyseh9/ZBFuCugRC1IhtCnuvkuZW67KswpHXLOtoceygR51ZU6KH/AmYV5yyfujPnpWsrXbNmdxeeOW1JKyoSIdLCE+1G3Esv8WBzG3ggAK3ipAkQPW0a0U6e/2aNCS48h0qpJlymvkqsFT8I3EK0d1Pj88SCjg469cBa6B0RElOEIv9LqE8PUcYqL7+4flnU3Xkf09qZdEmW2FgjafVqY1hVETx2iFmXLmFxv/wVgoEgu/7aa9DaL3IBbrgG6N8L8U4qp8Goz1DCiAW3zmtlbjwzv72TKj/YNrpKSDnmS+JjdJQQ2FbaQBhEI56KxibabC09jxYlebCvD0GXi8tR0Xzw8mVc/eM2KXiykgSXb3AyjggXbRez0AJSO7yG4aUYfKRZA68vau7uF57/GFzgCopvGwKflEPLQxZSxZquOhxrdE1bGmGzpYSR6kWeX6ba7q2uodqeD6vXA1lUNlpFhYwuXKcO9CCl9OeL2i7XCwChM3GjfenrD+N/DBCPTCNCwhR9vDl6u7omMZttzmBHx8wrxcUZvtLSdGVq3kQ6eQjL6KQKd4X01kH210pcOlnU0XFxdK0QHP0TMtNwdG70/l/ANg0djq2JtgAAAABJRU5ErkJggg==
      mediatype: image/png
  labels:
    alm-owner-amq-broker: activemq-artemis-operator
    operated-by: activemq-artemis-operator.v1.0.0
  selector:
    matchLabels:
      ActiveMQArtemis: example-activemqartemis
      application: example-activemqartemis-app
      operated-by: activemq-artemis-operator.v1.0.0
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - name: activemqartemises.broker.amq.io
        version: v1alpha1
        kind: ActiveMQArtemis
        description: An instance of Active MQ Artemis
        displayName: ActiveMQ Artemis
        resources:
          - kind: Service
            version: v1
          - kind: Deployment
            version: v1
        specDescriptors:
          - description: The desired number of member pods for ActiveMQArtemis mesh
            displayName: Size
            path: size
          - description: The Image
            displayName: Image
            path: image
      - name: activemqartemisaddresses.broker.amq.io
        version: v1alpha1
        kind: ActiveMQArtemisAddress
        description: Adding and removing queues via custom resource definitions
        displayName: ActiveMQ Artemis Address
        specDescriptors:
          - description: The Statefulset Name
            displayName: Statefulset Name
            path: statefulsetName
          - description: The Queue Name
            displayName: Queue Name
            path: queueName
          - description: The Address Name
            displayName: Address Name
            path: addressName
          - description: The Routing Type
            displayName: Routing Type
            path: routingType


  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: activemq-artemis-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - broker.amq.io
              resources:
                - '*'
              verbs:
                - '*'
      deployments:
        - name: activemq-artemis-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: activemq-artemis-operator
            template:
              metadata:
                labels:
                  name: activemq-artemis-operator
              spec:
                serviceAccountName: activemq-artemis-operator
                containers:
                  - name: activemq-artemis-operator
                    # Replace this with the built image name
                    image: quay.io/ahameed/activemq-artemis-operator:latest
                    command:
                      - /usr/local/bin/entrypoint
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "activemq-artemis-operator"