apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84733-20241008002724
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:dff7ca01bbef7d9e79e5caa80815eb68e92aca6c43ab82f276a7bd48a217d307
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-93765-20241008001246
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:3479e545e6185b29cc8d4fce93a440e5421fafb56cbd3cb51b7529892aba340e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84733-20241008002724
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:dff7ca01bbef7d9e79e5caa80815eb68e92aca6c43ab82f276a7bd48a217d307
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-93765-20241008001246
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:3479e545e6185b29cc8d4fce93a440e5421fafb56cbd3cb51b7529892aba340e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84733-20241008002724
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:dff7ca01bbef7d9e79e5caa80815eb68e92aca6c43ab82f276a7bd48a217d307
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-93765-20241008001246
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:3479e545e6185b29cc8d4fce93a440e5421fafb56cbd3cb51b7529892aba340e
