apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84142-20240914001902
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e2c9a497b141001b26bf4324de52c034545c6f1b1843c0951577146b7e391acc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-33438-20240914000513
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:d816c8d017f881894fed6154b6bcb729805c50ed8cf3b767302e42031237b49b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84142-20240914001902
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e2c9a497b141001b26bf4324de52c034545c6f1b1843c0951577146b7e391acc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-33438-20240914000513
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:d816c8d017f881894fed6154b6bcb729805c50ed8cf3b767302e42031237b49b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-84142-20240914001902
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e2c9a497b141001b26bf4324de52c034545c6f1b1843c0951577146b7e391acc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-33438-20240914000513
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:d816c8d017f881894fed6154b6bcb729805c50ed8cf3b767302e42031237b49b
