apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-21965-20241024001849
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:20255853764d9905ec2ae0f610e792368b553376bb41fb7e03a293d53288129a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-98521-20241024000234
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:2f123d30012d3cbbcdaa2ffccfb54a4e15b04d96960519f75c3fe4e868bf4b5a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-21965-20241024001849
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:20255853764d9905ec2ae0f610e792368b553376bb41fb7e03a293d53288129a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-98521-20241024000234
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:2f123d30012d3cbbcdaa2ffccfb54a4e15b04d96960519f75c3fe4e868bf4b5a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-21965-20241024001849
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:20255853764d9905ec2ae0f610e792368b553376bb41fb7e03a293d53288129a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-98521-20241024000234
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:2f123d30012d3cbbcdaa2ffccfb54a4e15b04d96960519f75c3fe4e868bf4b5a
