apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 7.11.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799

        # 7.11.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a

        # 7.11.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4.1697654363
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:0dde839c2dce7cb684094bf26523c8e16677de03149a0fff468b8c3f106e1f4f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5.1697648860
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:29f07006ad62023c20d34971cb3ae900349efae5ab2918aaa8e5647d788032be

        # 7.11.3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7113_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.3-1.1698107486
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:5e5d8b551ab8ca377e0bc939037970a2f31ee14e9f555853ebea2759d673895a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7113_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.3-1.1698106824
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:ade37271426ab8f543d72f8da3e9f663d665f9427379a2539fc9323f6897cc44

        # 7.12.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-73957-20231102002006
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1fd2c03ee881b67e8462ffaa5d428b6d157d26cb807d542732547e57d99ed4d9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-55192-20231102000927
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:46ce30c57db0bc6d318a0ba9e8f84428e53725c243cea4296bbda0bc64ddef97
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-73957-20231102002006
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1fd2c03ee881b67e8462ffaa5d428b6d157d26cb807d542732547e57d99ed4d9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-55192-20231102000927
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:46ce30c57db0bc6d318a0ba9e8f84428e53725c243cea4296bbda0bc64ddef97
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-73957-20231102002006
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:1fd2c03ee881b67e8462ffaa5d428b6d157d26cb807d542732547e57d99ed4d9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-55192-20231102000927
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:46ce30c57db0bc6d318a0ba9e8f84428e53725c243cea4296bbda0bc64ddef97
