apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 7.11.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.0-7.1687445595
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:b9f93c243ead118651083880786a81c624f390fcc3596c7ec5ebd55f34f95ea3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7110_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.0-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:25c3732e945b4bc3e9aca721ce709d0217339b065d9dac9afdb6202e9fd8a799

        # 7.11.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.1-2.1693372837
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:9c1ac38bf8eec67a3da57c3cc61105513776a749408cb287fe6448a17889de4e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7111_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.1-2.1693371471
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:40ccaf2bb2e0f8132f2541b39cb835f17b38050b3ca9232f0861fd5fcaf4324a

        # 7.11.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:a254399c6b5d188c7371fe100c9a3de3375fb02a138a4890b8522c8daa7bafcf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:67b91b937efa3e6115d9202645e2578e2fb6daeb05be15833a2d0b7b223aae6d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:a254399c6b5d188c7371fe100c9a3de3375fb02a138a4890b8522c8daa7bafcf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:67b91b937efa3e6115d9202645e2578e2fb6daeb05be15833a2d0b7b223aae6d
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.11.2-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:a254399c6b5d188c7371fe100c9a3de3375fb02a138a4890b8522c8daa7bafcf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7112_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.11.2-5
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:67b91b937efa3e6115d9202645e2578e2fb6daeb05be15833a2d0b7b223aae6d

        # 7.12.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-79768-20231011020609
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:32a4960437f7094ff8050470dcfb1f624784a45c2c7cb3fd0ec02c23eb5ceaa9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-64509-20231011013439
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:fdd2dec234cab77a25851e77464242d6994ef4150961f2ff6f0a40a90deb3515
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-79768-20231011020609
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:32a4960437f7094ff8050470dcfb1f624784a45c2c7cb3fd0ec02c23eb5ceaa9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-64509-20231011013439
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:fdd2dec234cab77a25851e77464242d6994ef4150961f2ff6f0a40a90deb3515
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:7.12.0-scratch-79768-20231011020609
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:32a4960437f7094ff8050470dcfb1f624784a45c2c7cb3fd0ec02c23eb5ceaa9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_7120_s390x
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.12.0-scratch-64509-20231011013439
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:fdd2dec234cab77a25851e77464242d6994ef4150961f2ff6f0a40a90deb3515
