apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-95564-20240822010903
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:494121cdbb1bdd51fad739d0a0550c61cb9f709bdcff9a2985cff39c2b34a1aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-22831-20240822005242
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:0b49a6c9a4e9768297ffcc2ff193944c0ca5515a7432e6cadf4d7f0638da5963
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-95564-20240822010903
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:494121cdbb1bdd51fad739d0a0550c61cb9f709bdcff9a2985cff39c2b34a1aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-22831-20240822005242
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:0b49a6c9a4e9768297ffcc2ff193944c0ca5515a7432e6cadf4d7f0638da5963
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-95564-20240822010903
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:494121cdbb1bdd51fad739d0a0550c61cb9f709bdcff9a2985cff39c2b34a1aa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-22831-20240822005242
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:0b49a6c9a4e9768297ffcc2ff193944c0ca5515a7432e6cadf4d7f0638da5963
