apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    metadata:
      labels:
        com.company: Red_Hat
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2023.Q2
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.11.0
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
