apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-50356-20240816002150
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:bf99064c359769762bce5c8114ded1b4d8d789b24589b01e8ebaa562aca164cc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-55228-20240816000800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:c111045433118ec7beb376e5129f3fd34315b4d30c270724715b302be4d7ae35
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-50356-20240816002150
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:bf99064c359769762bce5c8114ded1b4d8d789b24589b01e8ebaa562aca164cc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-55228-20240816000800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:c111045433118ec7beb376e5129f3fd34315b4d30c270724715b302be4d7ae35
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-50356-20240816002150
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:bf99064c359769762bce5c8114ded1b4d8d789b24589b01e8ebaa562aca164cc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-55228-20240816000800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:c111045433118ec7beb376e5129f3fd34315b4d30c270724715b302be4d7ae35
