apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # 8.0.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-68867-20240503041622
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e83588bb69c692935da58187937c8b1943be23051e67602ae890b2f2bf71b955
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-84396-20240503035330
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e91349c748d69beab3cb3139f13fe2dec2e23855a9a129b63c5f3c3f72821c1a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-68867-20240503041622
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e83588bb69c692935da58187937c8b1943be23051e67602ae890b2f2bf71b955
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-84396-20240503035330
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e91349c748d69beab3cb3139f13fe2dec2e23855a9a129b63c5f3c3f72821c1a
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-init-rhel8:8.0.0-scratch-68867-20240503041622
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:e83588bb69c692935da58187937c8b1943be23051e67602ae890b2f2bf71b955
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          #value: registry.redhat.io/amq8/amq-broker-rhel8:8.0.0-scratch-84396-20240503035330
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e91349c748d69beab3cb3139f13fe2dec2e23855a9a129b63c5f3c3f72821c1a
