apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "broker.amq.io/v1alpha1",
          "kind": "ActiveMQArtemisSecurity",
          "metadata": {
            "name": "ex-prop"
          },
          "spec": {
            "loginModules": {
              "propertiesLoginModules": [
                {
                  "name": "prop-module",
                  "users": [
                    {
                      "name": "bob",
                      "roles": [
                        "root"
                      ]
                    }
                  ]
                }
              ]
            },
            "securityDomains": {
              "brokerDomain": {
                "loginModules": [
                  {
                    "flag": "sufficient",
                    "name": "prop-module"
                  }
                ],
                "name": "activemq"
              }
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v1beta1",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "jolokiaAgentEnabled": false,
              "journalType": "nio",
              "managementRBACEnabled": true,
              "messageMigration": false,
              "persistenceEnabled": false,
              "requireLogin": false,
              "size": 2
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v1beta1",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "ex-aaoaddress"
          },
          "spec": {
            "addressName": "myAddress0",
            "queueName": "myQueue0",
            "routingType": "anycast"
          }
        },
        {
          "apiVersion": "broker.amq.io/v1beta1",
          "kind": "ActiveMQArtemisScaledown",
          "metadata": {
            "name": "ex-aaoscaledown"
          },
          "spec": {
            "localOnly": true
          }
        },
        {
          "apiVersion": "broker.amq.io/v1beta1",
          "kind": "ActiveMQArtemisSecurity",
          "metadata": {
            "name": "ex-prop"
          },
          "spec": {
            "loginModules": {
              "propertiesLoginModules": [
                {
                  "name": "prop-module",
                  "users": [
                    {
                      "name": "bob",
                      "roles": [
                        "root"
                      ]
                    }
                  ]
                }
              ]
            },
            "securityDomains": {
              "brokerDomain": {
                "loginModules": [
                  {
                    "flag": "sufficient",
                    "name": "prop-module"
                  }
                ],
                "name": "activemq"
              }
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "size": 2
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "ex-aaoaddress"
          },
          "spec": {
            "addressName": "myAddress0",
            "queueName": "myQueue0",
            "routingType": "anycast"
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisScaledown",
          "metadata": {
            "name": "ex-aaoscaledown"
          },
          "spec": {
            "localOnly": true
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha2",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "size": 2
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha2",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "ex-aaoaddress"
          },
          "spec": {
            "addressName": "myAddress0",
            "queueName": "myQueue0",
            "routingType": "anycast"
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha3",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "size": 2
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha3",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
            "name": "ex-aaoaddress"
          },
          "spec": {
            "addressName": "myAddress0",
            "queueName": "myQueue0",
            "routingType": "anycast"
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha4",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "size": 2
            }
          }
        },
        {
          "apiVersion": "broker.amq.io/v2alpha5",
          "kind": "ActiveMQArtemis",
          "metadata": {
            "name": "ex-aao"
          },
          "spec": {
            "deploymentPlan": {
              "image": "placeholder",
              "size": 2
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.28.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: activemq-artemis-operator.v8.0.0-opr-1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v1beta1
    - kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha1
    - kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha2
    - kind: ActiveMQArtemisAddress
      name: activemqartemisaddresses.broker.amq.io
      version: v2alpha3
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v1beta1
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha1
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha2
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha3
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha4
    - kind: ActiveMQArtemis
      name: activemqartemises.broker.amq.io
      version: v2alpha5
    - kind: ActiveMQArtemisScaledown
      name: activemqartemisscaledowns.broker.amq.io
      version: v1beta1
    - kind: ActiveMQArtemisScaledown
      name: activemqartemisscaledowns.broker.amq.io
      version: v2alpha1
    - kind: ActiveMQArtemisSecurity
      name: activemqartemissecurities.broker.amq.io
      version: v1alpha1
    - kind: ActiveMQArtemisSecurity
      name: activemqartemissecurities.broker.amq.io
      version: v1beta1
  description: Activemq Artemis Operator description. TODO.
  displayName: Activemq Artemis Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments:
      - label:
          control-plane: controller-manager
        name: amq-broker-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
              name: amq-broker-operator
          strategy:
            rollingUpdate:
              maxSurge: 1
              maxUnavailable: 1
            type: RollingUpdate
          template:
            metadata:
              labels:
                com.company: Red_Hat
                control-plane: controller-manager
                name: amq-broker-operator
                rht.comp: Broker_AMQ
                rht.comp_ver: 8.0.0
                rht.prod_name: Red_Hat_Integration
                rht.prod_ver: 2024.Q1
                rht.subcomp: broker-amq-operator
                rht.subcomp_t: application
            spec:
              containers:
              - args:
                - --zap-log-level=info
                - --zap-encoder=console
                - --zap-time-encoding=iso8601
                - --leader-elect
                command:
                - /home/activemq-artemis-operator/bin/entrypoint
                env:
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
                  value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8d191047a5fcc1d441041f6dc7a1e1d8648dcae8370087178d59835e9f173088
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
                  value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:a62f71699d98bea29b0902a346eff889c6bc89d9551cc235f93d7c52370249c3
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
                  value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8d191047a5fcc1d441041f6dc7a1e1d8648dcae8370087178d59835e9f173088
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
                  value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:a62f71699d98bea29b0902a346eff889c6bc89d9551cc235f93d7c52370249c3
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
                  value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8d191047a5fcc1d441041f6dc7a1e1d8648dcae8370087178d59835e9f173088
                - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
                  value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:a62f71699d98bea29b0902a346eff889c6bc89d9551cc235f93d7c52370249c3
                - name: OPERATOR_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['name']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: ENABLE_WEBHOOKS
                  value: "false"
                image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 8383
                  name: http-metrics
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  runAsNonRoot: true
                  seccompProfile:
                    type: RuntimeDefault
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: amq-broker-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - endpoints
          - events
          - persistentvolumeclaims
          - pods
          - routes
          - secrets
          - serviceaccounts
          - services
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - daemonsets
          - deployments
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisaddresses/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemises/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemisscaledowns/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities/finalizers
          verbs:
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - activemqartemissecurities/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - broker.amq.io
          resources:
          - pods
          verbs:
          - get
          - list
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - create
          - get
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - rolebindings
          - roles
          verbs:
          - create
          - delete
          - get
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          - routes/custom-host
          - routes/status
          verbs:
          - create
          - delete
          - get
          - list
          - update
          - watch
        serviceAccountName: amq-broker-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - activemq-artemis-operator
  links:
  - name: Activemq Artemis Operator
    url: https://activemq-artemis-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  relatedImages:
  - image: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8d191047a5fcc1d441041f6dc7a1e1d8648dcae8370087178d59835e9f173088
    name: ""
  - image: registry.redhat.io/amq7/amq-broker-rhel8@sha256:a62f71699d98bea29b0902a346eff889c6bc89d9551cc235f93d7c52370249c3
    name: ""
  version: 8.0.0-opr-1
