apiVersion: broker.amq.io/v1alpha1
kind: ActiveMQArtemis
metadata:
  name: example-activemqartemis
  labels:
    ActiveMQArtemis: example-activemqartemis
    application: example-activemqartemis-app
spec:
  # Add fields here
  size: 4
  image: registry.access.redhat.com/amq-broker-7/amq-broker-72-openshift:1.3-4
  sslEnabled: false
  sslConfig:
    secretName: amq-app-secret
    trustStoreFilename: broker.ts
    trustStorePassword: changeit
    keystoreFilename: broker.ks
    keyStorePassword: changeit