kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: activemqartemisaddresses.broker.amq.io
spec:
  subresources:
    status: {}
  names:
    plural: activemqartemisaddresses
    singular: activemqartemisaddress
    kind: ActiveMQArtemisAddress
    listKind: ActiveMQArtemisAddressList
  scope: Namespaced
  conversion:
    strategy: None
  preserveUnknownFields: true
  version: v2alpha3
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - addressName
            - queueName
            - routingType
          properties:
            addressName:
              type: string
            queueName:
              type: string
            routingType:
              type: string
            removeFromBrokerOnDelete:
              type: boolean
            applyToCrNames:
              description: >-
                Apply to the broker crs in the current namespace
                A value of * means applying to all broker crs.
                Default apply to all broker crs.
              type: array
              minItems: 0
              items:
                type: string
        status:
          type: object
  versions:
    - name: v2alpha3
      served: true
      storage: true
    - name: v2alpha2
      served: true
      storage: false
    - name: v2alpha1
      served: true
      storage: false
    - name: v1alpha2
      served: true
      storage: false
    - name: v1alpha1
      served: false
      storage: false
  group: broker.amq.io
