apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: amq-broker-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: amq-broker-operator
subjects:
- kind: ServiceAccount
  name: amq-broker-operator
  namespace: amq-broker-operator
