apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-artemis-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: activemq-artemis-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: activemq-artemis-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        - '--zap-encoder console'
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init
          value: registry.redhat.io/amq7/amq-broker-init-rhel7:0.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_211
          value: registry.redhat.io/amq7/amq-broker:7.8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_212
          value: registry.redhat.io/amq7/amq-broker:7.8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_213
          value: registry.redhat.io/amq7/amq-broker:7.8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel7:0.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_211_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_212_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_213_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel7:0.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_211_s390x
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_212_s390x
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_213_s390x
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        image: registry.redhat.io/amq7/amq-broker-rhel7-operator:0.18
        imagePullPolicy: Always
        name: activemq-artemis-operator
        resources: {}
      serviceAccountName: activemq-artemis-operator
