apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 8.0.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2024.Q3
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:5fa808ab486edfede48e48aa2b7905e8c146f4337f7e557e5d7b59b0b1a07aa8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:11d4551d5b622f7e3d0de0e485736f01e65b289a6a874a4cb046f4a120587f73
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:5fa808ab486edfede48e48aa2b7905e8c146f4337f7e557e5d7b59b0b1a07aa8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:11d4551d5b622f7e3d0de0e485736f01e65b289a6a874a4cb046f4a120587f73
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:5fa808ab486edfede48e48aa2b7905e8c146f4337f7e557e5d7b59b0b1a07aa8
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:11d4551d5b622f7e3d0de0e485736f01e65b289a6a874a4cb046f4a120587f73
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq8/amq-broker-rhel8-operator@sha256:6f47b5b52fe9dedc84b41771d48d402ca8395cf0b6fb1aac0e83862655b9c79f
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
