apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level info'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
          # to watch all namespaces use '*' or empty ''
          # to watch multiple namespaces use comma separated list 'ns1,ns2'
          # default is to watch the operator's namespace (backward compatibility)
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # By default the *_782 values are utilized.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # X86_64 / AMD64 / default
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:f58678f03a250dbb296ebeb112c9150340155799ba4dad9e90bf347b9ed0ca7b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:90d14fd51dad277404dfaa9a6fbd47084996a7f078e7e6de2c5ad126a87cf0e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.4-3
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:04357feeb334c2e0da26600ec24a7327c9223acdd904260a3b97bf5773b023fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-3
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0d857b95084e39c011651be89482d4dcc77c2d1c3ac3c6a819f3c9d5a57a425f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-4
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:65efcd7f7d265225ff1f101b098afa0dfffaf5391424a23ebcce5f9b39818e59
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.9-4
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:28b6864780d29bd24867ed51b4b16613705249ca40ddd202c7bfcb6469a2feb7

        # PPC64LE
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-1
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:079ecb9878686e6960bde87d49af9e24d58aa8edcc57be5147509bb9966cc20e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:bbfa637fdd96f3849240fae665a62426e395835834e397abfb07da3abc09b273
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-1
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:46f1a49e01763b45d2e394da082f31ff0fafe4413fff456e9ecb64dac91c3a88

        # S390X
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_790_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.4-1
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:079ecb9878686e6960bde87d49af9e24d58aa8edcc57be5147509bb9966cc20e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:bbfa637fdd96f3849240fae665a62426e395835834e397abfb07da3abc09b273
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_790_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.9-1
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:46f1a49e01763b45d2e394da082f31ff0fafe4413fff456e9ecb64dac91c3a88

        #image: registry.redhat.io/amq7/amq-broker-rhel8-operator:7.9-2
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:050a98dce83a60a02238d37de32d71ca7ed59002f5762536743b115541d8204b

        # If floating tags are configured above you may want to set this to true.
        #imagePullPolicy: Always

        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
