apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 7.x.x
        rht.prod_name: Red_Hat_Integration
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8e6cc30f49f61ef0e5a11def8f375242291bf812b391e2c019be5070e86f84b0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d348f01315a4644ee16ea6419b6d4553f26b88766dd31425e147a6d6e955c0c2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8e6cc30f49f61ef0e5a11def8f375242291bf812b391e2c019be5070e86f84b0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d348f01315a4644ee16ea6419b6d4553f26b88766dd31425e147a6d6e955c0c2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:8e6cc30f49f61ef0e5a11def8f375242291bf812b391e2c019be5070e86f84b0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:d348f01315a4644ee16ea6419b6d4553f26b88766dd31425e147a6d6e955c0c2
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
