apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level info'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # By default the *_781 values are utilized.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # X86_64 / AMD64 / default
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:f58678f03a250dbb296ebeb112c9150340155799ba4dad9e90bf347b9ed0ca7b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-3
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0d857b95084e39c011651be89482d4dcc77c2d1c3ac3c6a819f3c9d5a57a425f

        # PPC64LE
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa

        # S390X
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa

        #image: registry.redhat.io/amq7/amq-broker-rhel8-operator:7.8-7
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:33cdbac36593ce437b4f2c0a80008ababc1592f0441ffc4b1872ceb274d2ad42

        # If floating tags are configured above you may want to set this to true.
        #imagePullPolicy: Always

        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
