apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init:0.3-1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_770
          value: registry.redhat.io/amq7/amq-broker:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_780
          value: registry.redhat.io/amq7/amq-broker:7.8-12
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift:7.8-16
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_ppc64le
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init:0.3-2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_770_ppc64le
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_780_ppc64le
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_s390x
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init:0.3-2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_770_s390x
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_780_s390x
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-4

        image: registry-proxy.engineering.redhat.com/rh-osbs/amq7-amq-broker-rhel8-operator:0.19
        imagePullPolicy: Always
        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
