apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 8.0.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2024.Q3
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:66999dcced85cb1ff306b531bc082c4dc01844fc3ab2fa6aa0cc32b7ea7bcafe
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:4154d24e1c1dcb43e658f59774553581f0f0144c138ef3cb2cc1ed5b4e10af8e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:66999dcced85cb1ff306b531bc082c4dc01844fc3ab2fa6aa0cc32b7ea7bcafe
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:4154d24e1c1dcb43e658f59774553581f0f0144c138ef3cb2cc1ed5b4e10af8e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:66999dcced85cb1ff306b531bc082c4dc01844fc3ab2fa6aa0cc32b7ea7bcafe
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:4154d24e1c1dcb43e658f59774553581f0f0144c138ef3cb2cc1ed5b4e10af8e
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq8/amq-broker-rhel8-operator@sha256:58a102b7e3b48b39d682d0f06f70f74aa6923fde34a07d23ce73a14db3ff12b5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
