apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level info'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # By default the *_781 values are utilized.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # X86_64 / AMD64 / default
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init-rhel8:0.3-3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-rhel8:7.8-3

        # PPC64LE
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init-openj9-11-rhel8:0.3-3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-8

        # S390X
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-init-openj9-11-rhel8:0.3-3
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          value: registry-proxy.engineering.redhat.com/rh-osbs/amq-broker-7-amq-broker-78-openshift-openj9-11-rhel8:7.8-8

        image: registry-proxy.engineering.redhat.com/rh-osbs/amq7-amq-broker-rhel8-operator:7.8-6

        # If floating tags are configured above you may want to set this to true.
        #imagePullPolicy: Always

        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
