apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level info'
        - '--zap-encoder console'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        # Below are the environment variables that inform the operator what container images to utilize for each product version.
        # By default the *_782 values are utilized.
        # The *Init* values refer to the init container images that configure the broker configuration prior to broker container start.
        # The *Kubernetes* values refer to the broker on openshift container that runs the broker itself.
        # NOTE: Below are the original image:tag values and equivalent SHA image references. The SHA values are unique to the specific
        #       container tag utilized during operator bundle build time.

        # X86_64 / AMD64 / default
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:f58678f03a250dbb296ebeb112c9150340155799ba4dad9e90bf347b9ed0ca7b
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-7
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:61e5a8c1e46f1c18648e0406e2a57c52f911979079020cc57c7a4b06a56940bb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-10
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:c3e7a9ecfd125e067e7934e50bcede05bee02def746c925280509538e1f55bf9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_784
          #value: registry.redhat.io/amq7/amq-broker-init-rhel8:0.3-11
          value: registry.redhat.io/amq7/amq-broker-init-rhel8@sha256:a7abc339f2fcaeb07c2eee0241c90967e0c15d98b23729094f1ae91e2d5c1b3e
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-3
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:0d857b95084e39c011651be89482d4dcc77c2d1c3ac3c6a819f3c9d5a57a425f
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:67ae74e72927557c55611d0248347b2099b117ac1aa245dac05856fe782fb59c
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-12
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:75d5772c792a7c795281acec3d59e90021c109e9d7d1110868be0b882768aefb
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_784
          #value: registry.redhat.io/amq7/amq-broker-rhel8:7.8-13
          value: registry.redhat.io/amq7/amq-broker-rhel8@sha256:17ca3276b6c7e9bfa3cfe2a50ee1794e9b3c823227fe78df52394d1c4220b384

        # PPC64LE
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-5
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:56282c6a461e945a83bffb13d3f3d8d9621800f0fc9cd755a75d21eacd8f5fbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:bbfa637fdd96f3849240fae665a62426e395835834e397abfb07da3abc09b273
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_ppc64le
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-15
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:34ab1f66d8daa544e3823464383e9788e307665c875499838fbed95f3a74a4dd

        # S390X
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-3
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:5ff28e3062d3eabb9f52d8271b837fdab06cafbd8b8f732b1bc00de49ad69aad
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-4
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:326d8722c23aa8851cdad3fdc2d9c4823cd3f63d1e4668cf3a9a4c273a0b84e1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_783_s390x
          #value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8:0.3-5
          value: registry.redhat.io/amq7/amq-broker-init-openj9-11-rhel8@sha256:56282c6a461e945a83bffb13d3f3d8d9621800f0fc9cd755a75d21eacd8f5fbf
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_781_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-8
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:f2651cb097eb631fc6af90e4a8404d36516aa2205c546125bf0c37739ab525fa
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_782_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-12
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:bbfa637fdd96f3849240fae665a62426e395835834e397abfb07da3abc09b273
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_783_s390x
          #value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8:7.8-15
          value: registry.redhat.io/amq7/amq-broker-openj9-11-rhel8@sha256:34ab1f66d8daa544e3823464383e9788e307665c875499838fbed95f3a74a4dd

        #image: registry.redhat.io/amq7/amq-broker-rhel8-operator:7.8-15
        image: registry.redhat.io/amq7/amq-broker-rhel8-operator@sha256:a78b98811f84521b973c440b057af4e96fabb072d8fbb9d650d6239a506c0c9b

        # If floating tags are configured above you may want to set this to true.
        #imagePullPolicy: Always

        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
