apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: amq-broker-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        com.company: Red_Hat
        control-plane: controller-manager
        name: amq-broker-operator
        rht.comp: Broker_AMQ
        rht.comp_ver: 8.0.0
        rht.prod_name: Red_Hat_Integration
        rht.prod_ver: 2024.Q4
        rht.subcomp: broker-amq-operator
        rht.subcomp_t: application
    spec:
      containers:
      - args:
        - --zap-log-level=info
        - --zap-encoder=console
        - --zap-time-encoding=iso8601
        - --leader-elect
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:9f9d923affdf597847787c64de86eb83ff3bb00537a673363c732fa4fd8a09cd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e33f9ca35f0c3dd1bd37bcf556296571482526cb53cf1681e9c3da83f71e4fcc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:9f9d923affdf597847787c64de86eb83ff3bb00537a673363c732fa4fd8a09cd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_ppc64le
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e33f9ca35f0c3dd1bd37bcf556296571482526cb53cf1681e9c3da83f71e4fcc
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_800_s390x
          value: registry.redhat.io/amq8/amq-broker-init-rhel8@sha256:9f9d923affdf597847787c64de86eb83ff3bb00537a673363c732fa4fd8a09cd
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_800_s390x
          value: registry.redhat.io/amq8/amq-broker-rhel8@sha256:e33f9ca35f0c3dd1bd37bcf556296571482526cb53cf1681e9c3da83f71e4fcc
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: registry.redhat.io/amq8/amq-broker-rhel8-operator@sha256:65aa8dcbc8e58f27a7c19dc387b74be8bc999e68c879a206bd4b233cbf3bdf4e
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        ports:
        - containerPort: 8383
          name: http-metrics
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: amq-broker-controller-manager
      terminationGracePeriodSeconds: 10
