apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-broker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: amq-broker-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: amq-broker-operator
    spec:
      containers:
      - args:
        # Explicitly set the logging level.
        # Valid values are debug, info, and error
        # from most to least.
        # If running entrypoint_debug then use '-- --zap-level debug'
        - '--zap-level debug'
        command:
        - /home/amq-broker-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: BROKER_IMAGE_760
          #value: registry.redhat.io/amq7/amq-broker:7.6
          value: docker-registry.default.svc:5000/entmqbr-4064-1/amq-broker-7-amq-broker-77-openshift:7.7
        - name: BROKER_IMAGE_750
          #value: registry.redhat.io/amq7/amq-broker:7.5
          value: docker-registry.default.svc:5000/entmqbr-4064-1/amq-broker-7-amq-broker-77-openshift:7.7
        - name: BROKER_IMAGE_770
          #value: registry.redhat.io/amq7/amq-broker:7.7
          value: docker-registry.default.svc:5000/entmqbr-4064-1/amq-broker-7-amq-broker-77-openshift:7.7
        #image: registry.redhat.io/amq7/amq-broker-rhel7-operator:0.17
        image: docker-registry.default.svc:5000/entmqbr-4064-1/amq-broker-operator:latest
        imagePullPolicy: Always
        name: amq-broker-operator
        resources: {}
      serviceAccountName: amq-broker-operator
